apiVersion: v1
kind: Secret
metadata:
     name: 12-maria-sulca-secret
type: Opaque
data:
     # base64 encoded values (ejemplo: admin -> YWRtaW4=, password -> cGFzc3dvcmQ=)
     BASIC_AUTH_USER: YWRtaW4=
     BASIC_AUTH_PASSWORD: cGFzc3dvcmQ=
