apiVersion: v1
kind: Service
metadata:
     name: maria-sulca-users-service
     labels:
          app: 12-maria-sulca-users
spec:
     type: NodePort
     selector:
          app: 12-maria-sulca-users
     ports:
          - protocol: TCP
            port: 9083
            targetPort: 9083
            nodePort: 30083
