apiVersion: v1
kind: Service
metadata:
     name: maria-sulca-front-service
     labels:
          app: 12-maria-sulca-front
spec:
     type: NodePort
     selector:
          app: 12-maria-sulca-front
     ports:
          - protocol: TCP
            port: 80
            targetPort: 80
            nodePort: 30081
